(()=>{
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Number(n||0)),pct=n=>`${(Number(n||0)*100).toFixed(1)}%`,medal=n=>n===1?'🏆':n===2?'🥈':n===3?'🥉':`#${n}`;
document.querySelector('.nav-toggle')?.addEventListener('click',()=>document.querySelector('.nav')?.classList.toggle('open'));
async function load(){const [history,franchises]=await Promise.all([fetch('data/history.json').then(r=>{if(!r.ok)throw Error('history.json unavailable');return r.json()}),fetch('data/franchises.json').then(r=>{if(!r.ok)throw Error('franchises.json unavailable');return r.json()})]);return{history,franchises,byId:Object.fromEntries(franchises.map(x=>[String(x.franchiseId),x]))}}
function aggregate(c){const out={};c.history.forEach(r=>{const id=String(r.franchiseId),x=out[id]??={id,name:c.byId[id]?.currentName||r.teamName,seasons:0,wins:0,losses:0,ties:0,titles:0,runnerUps:0,thirds:0,playoffs:0,finishTotal:0,pf:0,pa:0};x.seasons++;x.wins+=+r.wins||0;x.losses+=+r.losses||0;x.ties+=+r.ties||0;x.finishTotal+=+r.finalRank||0;x.pf+=+r.pointsFor||0;x.pa+=+r.pointsAgainst||0;if(+r.finalRank===1)x.titles++;if(+r.finalRank===2)x.runnerUps++;if(+r.finalRank===3)x.thirds++;if(+r.playoffSeed>0)x.playoffs++});return Object.values(out).map(x=>({...x,winPct:x.wins/(x.wins+x.losses+x.ties||1),playoffRate:x.playoffs/(x.seasons||1),avgFinish:x.finishTotal/(x.seasons||1)}))}
function trophySort(a,b){return b.titles-a.titles||b.runnerUps-a.runnerUps||b.thirds-a.thirds||b.playoffRate-a.playoffRate||b.winPct-a.winPct||a.name.localeCompare(b.name)}
function table(headers,rows){return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function metric(label,value,detail=''){return `<article class="objective-card"><div class="record-label">${label}</div><div class="objective-value">${value}</div><div class="record-detail">${detail}</div></article>`}
function render(c,id){const fid=String(id),f=c.byId[fid],rows=c.history.filter(r=>String(r.franchiseId)===fid).sort((a,b)=>b.season-a.season),all=aggregate(c).sort(trophySort),x=all.find(v=>v.id===fid),rank=all.findIndex(v=>v.id===fid)+1;if(!f||!x)throw Error('Franchise was not found');history.replaceState(null,'',`franchise.html?id=${fid}`);$('#franchise-header').innerHTML=`<div class="section-heading"><div><p class="eyebrow">Franchise ${fid}</p><h2>${f.currentName}</h2></div><span class="scope-pill">${f.firstSeason}–${f.lastSeason}</span></div>`;$('#franchise-objective-metrics').innerHTML=metric('Trophy rank',`#${rank}`,`${x.titles} titles • ${x.runnerUps} runner-up • ${x.thirds} third`)+metric('Playoff rate',pct(x.playoffRate),`${x.playoffs} of ${x.seasons} seasons`)+metric('Career win %',pct(x.winPct),`${x.wins}-${x.losses}-${x.ties}`)+metric('Average finish',x.avgFinish.toFixed(2),'Lower is better')+metric('Seasons played',x.seasons,'Sample size');$('#franchise-timeline').innerHTML=[...rows].reverse().map(r=>`<a class="timeline-season finish-${Math.min(+r.finalRank,8)}" href="history.html?season=${r.season}" title="${r.season}: final position ${r.finalRank}"><span>${r.season}</span><strong>${medal(+r.finalRank)}</strong><small>${r.wins}-${r.losses}</small></a>`).join('');$('#franchise-seasons').innerHTML=table(['Season','Name','Owner','Final','Record','PF','PA'],rows.map(r=>`<tr><td>${r.season}</td><td>${r.teamName}</td><td>${r.owner||'—'}</td><td class="${+r.finalRank===1?'champion':''}">${medal(+r.finalRank)}</td><td>${r.wins}-${r.losses}-${r.ties}</td><td>${fmt(r.pointsFor)}</td><td>${fmt(r.pointsAgainst)}</td></tr>`));$('#franchise-identity').innerHTML=`<p><strong>Current name</strong><br>${f.currentName}</p><p><strong>Known names</strong></p><ul class="identity-list">${f.historicalNames.map(n=>`<li>${n}</li>`).join('')}</ul><p><strong>Owners in history</strong></p><ul class="identity-list">${[...new Set(rows.map(r=>r.owner).filter(Boolean))].map(n=>`<li>${n}</li>`).join('')}</ul>`}
async function run(){const c=await load(),select=$('#franchise-select'),requested=new URLSearchParams(location.search).get('id'),initial=requested&&c.byId[requested]?requested:String(c.franchises[0].franchiseId);select.innerHTML=c.franchises.map(f=>`<option value="${f.franchiseId}" ${String(f.franchiseId)===initial?'selected':''}>${f.currentName}</option>`).join('');select.addEventListener('change',e=>render(c,e.target.value));render(c,initial);const dialog=$('#ranking-info');document.querySelector('[data-info="franchise"]')?.addEventListener('click',()=>dialog.showModal());document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()})}
run().catch(e=>document.querySelector('main').insertAdjacentHTML('afterbegin',`<div class="error"><strong>Data could not be loaded.</strong><br>${e.message}</div>`));
})();
