(()=>{
const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Number(n||0)), pct=n=>`${(Number(n||0)*100).toFixed(1)}%`, medal=n=>n===1?'🏆':n===2?'🥈':n===3?'🥉':`#${n}`;
const info={
 trophy:{title:'Trophy Ranking',body:'<p>The Trophy Ranking is championship-first. Franchises are sorted by:</p><ol><li>Championships</li><li>Runner-up finishes</li><li>Third-place finishes</li><li>Playoff rate, only as a further tie-break</li><li>Career win percentage, only as a final tie-break</li></ol><p><strong>No weighted score is used.</strong> A franchise with a championship is always ranked above a franchise with no championship.</p>'},
 consistency:{title:'Consistency Overview',body:'<p>Consistency is shown through separate objective measures rather than one combined index:</p><ul><li><strong>Playoff rate:</strong> playoff appearances divided by seasons played.</li><li><strong>Career win percentage:</strong> wins divided by wins, losses and ties.</li><li><strong>Average finish:</strong> mean final position across completed seasons. Lower is better.</li></ul><p>Seasons played is displayed beside these rates so newer and long-running franchises can be interpreted fairly.</p>'},
 franchise:{title:'Franchise Metrics',body:'<p><strong>Trophy Rank</strong> follows the championship-first ranking used on Hall of Fame.</p><p><strong>Playoff Rate</strong>, <strong>Win Percentage</strong> and <strong>Average Finish</strong> are shown separately. They are not blended into a subjective score.</p><p><strong>Seasons Played</strong> provides the sample-size context for all rates.</p>'}
};
function setupDialog(){const d=$('#ranking-info');if(!d)return;document.addEventListener('click',e=>{const b=e.target.closest('[data-info]');if(b){const x=info[b.dataset.info];$('#ranking-info-title').textContent=x.title;$('#ranking-info-body').innerHTML=x.body;d.showModal()}if(e.target.closest('.dialog-close'))d.close()});d.addEventListener('click',e=>{if(e.target===d)d.close()})}
async function data(){const [h,f]=await Promise.all([fetch('data/history.json').then(r=>r.json()),fetch('data/franchises.json').then(r=>r.json())]);return{history:h,franchises:f,byId:Object.fromEntries(f.map(x=>[String(x.franchiseId),x]))}}
function aggregate(c){const out={};c.history.forEach(r=>{const id=String(r.franchiseId),x=out[id]??={id,name:c.byId[id]?.currentName||r.teamName,seasons:0,wins:0,losses:0,ties:0,titles:0,runnerUps:0,thirds:0,playoffs:0,finishTotal:0};x.seasons++;x.wins+=+r.wins||0;x.losses+=+r.losses||0;x.ties+=+r.ties||0;x.finishTotal+=+r.finalRank||0;if(+r.finalRank===1)x.titles++;if(+r.finalRank===2)x.runnerUps++;if(+r.finalRank===3)x.thirds++;if(+r.playoffSeed>0)x.playoffs++});return Object.values(out).map(x=>({...x,winPct:x.wins/(x.wins+x.losses+x.ties||1),playoffRate:x.playoffs/(x.seasons||1),avgFinish:x.finishTotal/(x.seasons||1)}))}
function trophySort(a,b){return b.titles-a.titles||b.runnerUps-a.runnerUps||b.thirds-a.thirds||b.playoffRate-a.playoffRate||b.winPct-a.winPct||a.name.localeCompare(b.name)}
function table(headers,rows){return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function renderHall(c){const a=aggregate(c).sort(trophySort);$('#trophy-podium').innerHTML=a.slice(0,3).map((x,i)=>`<article class="trophy-card place-${i+1}"><div class="trophy-medal">${medal(i+1)}</div><h3><a href="franchise.html?id=${x.id}">${x.name}</a></h3><div class="trophy-count">${x.titles}<small> championship${x.titles===1?'':'s'}</small></div><p>${x.runnerUps} runner-up • ${x.thirds} third</p></article>`).join('');$('#trophy-table').innerHTML=table(['Rank','Franchise','Titles','Runner-up','Third','Playoffs','Seasons'],a.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><a class="text-link" href="franchise.html?id=${x.id}">${x.name}</a></td><td class="champion"><strong>${x.titles}</strong></td><td>${x.runnerUps}</td><td>${x.thirds}</td><td>${x.playoffs}</td><td>${x.seasons}</td></tr>`));const consistent=[...a].sort((x,y)=>y.playoffRate-x.playoffRate||y.winPct-x.winPct||x.avgFinish-y.avgFinish);$('#consistency-table').innerHTML=table(['Franchise','Seasons','Playoff rate','Win %','Average finish'],consistent.map(x=>`<tr><td><a class="text-link" href="franchise.html?id=${x.id}">${x.name}</a></td><td>${x.seasons}</td><td>${pct(x.playoffRate)}</td><td>${pct(x.winPct)}</td><td>${x.avgFinish.toFixed(2)}</td></tr>`))}
function metric(label,value,detail=''){return `<article class="objective-card"><div class="record-label">${label}</div><div class="objective-value">${value}</div><div class="record-detail">${detail}</div></article>`}
function renderFranchise(c,id){const a=aggregate(c).sort(trophySort),x=a.find(v=>v.id===String(id));if(!x)return;const rank=a.findIndex(v=>v.id===String(id))+1;$('#franchise-objective-metrics').innerHTML=metric('Trophy rank',`#${rank}`,`${x.titles} titles • ${x.runnerUps} runner-up • ${x.thirds} third`)+metric('Playoff rate',pct(x.playoffRate),`${x.playoffs} of ${x.seasons} seasons`)+metric('Career win %',pct(x.winPct),`${x.wins}-${x.losses}-${x.ties}`)+metric('Average finish',x.avgFinish.toFixed(2),'Lower is better')+metric('Seasons played',x.seasons,'Sample size')}
async function run(){setupDialog();const c=await data(),page=document.body.dataset.page;if(page==='trophy')renderHall(c);if(page==='franchise'){const select=$('#franchise-select'),initial=new URLSearchParams(location.search).get('id')||select?.value||String(c.franchises[0].franchiseId);renderFranchise(c,initial);select?.addEventListener('change',e=>renderFranchise(c,e.target.value))}}
run().catch(e=>{const target=$('#trophy-table')||$('#franchise-objective-metrics');if(target)target.innerHTML=`<div class="error">${e.message}</div>`})
})();
